### ISSUE TITLE
puli.json in git project

### ISSUE THREAD

**Issue by DerStoffel** [puli/issues#79] opened 2015-06-22 14:00 UTC
I am deploying a sf2 application with env=prod.
Since I use custom path-mappings in my puli.json this file is versioned along with the project.

Deploying sf2 in dev is no problem at all, and therefore the puli.json is often pushed to git with the packages used in dev mode. Hence, there are packages referenced only used in dev (also in SF AppKernel).

Now, I am deploying my sf2 app in prod environment and all require-dev dependencies in composer are left out. puli.json is altered by composer with the used packages only used in prod leaving a altered puli.json in my prod environment.

This makes deploying with git and ansible quite feasible. Any hints?

**Comment by webmozart** [comment] 2015-06-23 15:20
Thanks @DerStoffel for reporting this issue! Currently, environments are not supported by Puli. A solution would be to add separate normal packages from dev packages in puli.json. `--dev` and `--no-dev` options could be added to all commands that need to know about the environment, for example:

```
$ puli build --no-dev
```

What do you think?

**Comment by DerStoffel** [comment] 2015-06-23 17:54
Due to the familiarity from composer I'd love to see a possibility for exactly, what you describe. Some sort of "require-dev" or similar.

**Comment by stedekay** [comment] 2015-06-24 08:27
+1
This is a great idea!

**Comment by webmozart** [comment] 2015-06-25 17:19
See #81, #82 and #83 for implementation ideas.

ping @niklongstone

**Comment by niklongstone** [comment] 2015-06-25 18:55
cool, I am oriented to try something common from the user perspective like --dev.
I will be back with some rough implementations soon.

**Comment by webmozart** [comment] 2015-06-26 11:04
@niklongstone The tickets need to be implemented in order, as one builds on top of the other. Looking forward to your PRs :)

**Comment by webmozart** [comment] 2015-07-23 10:26
I'm closing this as a duplicate of the other issues.

**Closed by webmozart** 2015-07-23 10:26 UTC
Labels: Feature

**Comment by webmozart** [comment] 2015-08-24 10:19
This is fixed now. :)
