### ISSUE TITLE
Puli.json is hard to read and prone to change

### ISSUE THREAD

**Issue by mnapoli** [puli/issues#118] opened 2015-09-14 10:16 UTC
Hi, let me explain on the issue title that isn't very clear: after using Puli a little, `puli.json` is a bit of a small annoyance. It behaves more like `composer.lock` than `composer.json`: the `packages` entry is very large and contains one entry per composer dependency (even sub-dependencies of the one we require).

That has the consequences of:

- making it hard to read and understand (which for users new to Puli make it seem very obscure)
- changing every time we require a new Composer dependency (so it's kind of an unrelated change in git commits)

So this is not a really big issue, but rather a "developer experience" issue. What is the purpose of the `packages` entry? Can this content be moved to the `.puli/` directory in order to keep `puli.json` clean, understandable and less prone to change?

**Comment by webmozart** [comment] 2015-10-02 15:29
Hi @mnapoli :) If Puli relied on composer.json/composer.lock, there would be a lot of additional parsing going on every time you fire the puli command. Also, Puli would be directly coupled to Composer and break if Composer changed its file format or PHP API. Hence Puli was designed to be decoupled from Composer, which has the additional benefit that you can install Puli packages that have been installed through something else but Composer or are simply located somewhere on your file system.

Since Puli needs to know where your packages are, each `puli.json` contains a `packages` key with the names of those packages and their location. The Composer Plugin keeps a part of that entry (namely the packages with the `installer` set to `composer`) in sync with your composer.json file.

If we moved the information about the installed packages to a separate file that is not versioned, you lose the possibility of installing non-Composer packages. Do we really want that?

**Comment by mnapoli** [comment] 2015-10-02 15:59
Hi! I'm not sure we are discussing the same thing :/ I'm not saying to store anything in composer.json or composer.lock, but rather that puli.json *behaves like* composer.lock (i.e. changes a lot, not readable, etc.).

It would be great (if possible) to move info that is generated to somewhere not in git (i.e. in `.puli/`).

> If we moved the information about the installed packages to a separate file that is not versioned, you lose the possibility of installing non-Composer packages.

Isn't the `packages` key for packages installed with Composer? For packages not installed with composer, then there is the `path-mappings` key? (or am I mixing things up?)

So what I'm suggesting is that in the end what's in `puli.json` is stable (just like what's in composer.json), and what's changed for other reasons (composer packages) is store ideally outside of git. I'm not sure if I'm being really clear :/

**Comment by webmozart** [comment] 2015-10-02 16:02
Seems like you are indeed mixing things up a bit :) You can install packages in Puli with this command:

```
puli package --install path/to/package package/name
```

This package will be added to the "packages" key. The Composer Plugin does exactly that: call this command to register the Composer packages with Puli. But from the perspective of Puli, packages are not auto-generated: Someone somewhen called `puli package --install` to install each package.

However I agree that 95% of the users will use Composer only and not manually install packages. For those cases, having the packages in a separate file that is not versioned could indeed be nice.

**Comment by mnapoli** [comment] 2015-10-02 16:47
Ah ok thanks for explaining. So indeed it could be:

- store user-configured packages in `puli.json`
- store "auto-generated" packages in `.puli/…` (by auto-generated I mean added here by the Composer plugin)

Did I get it right?

**Comment by webmozart** [comment] 2015-10-05 09:42
Yes :) That solution is a bit more complicated than moving all packages to `.puli/...`, regardless of whether they are automatically or manually installed. I'd go with a simple solution first.

**Comment by webmozart** [comment] 2015-10-08 16:31
I just recalled one more thing that might be a problem here. The "packages" key also stores settings for individual packages. For example, if you disable a binding of a package, that's stored under the "packages" key. Such settings *should* always be distributed with the project, so I'm not sure whether moving "packages" to a separate, unversioned file makes so much sense.

**Comment by mnapoli** [comment] 2015-10-09 06:47
I see. Honestly I would say I'm fine to close this issue. It's a lot of work and maybe more subjective than objective in how much it's needed (I'm the only one complaining about it for now). I thought I would have time to work on this myself this friday but unfortunately I won't be able to join the coding session in the end. So feel free to close, unless you (or someone else) want this changed.

**Comment by webmozart** [comment] 2015-10-09 08:43
Ok. I'll close this for now and keep it in mind for later.

**Closed by webmozart** 2015-10-09 08:43 UTC
Labels: Feature, Manager
