### ISSUE TITLE
Symfony 3 + Puli + composer require: PULI_FACTORY_CLASS

### ISSUE THREAD

**Issue by devigner** [puli/issues#183] opened 2016-02-14 21:33 UTC
After issue #180 was resolved I still got the error but **only** in the following matter:

    $ composer require <any>/<any>

Results in the already famous (for me) error:

`
 ./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: constant(): Couldn't find constant PULI_FACTORY_CLASS

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

    [Symfony\Component\Debug\Exception\ContextErrorException]
    Warning: constant(): Couldn't find constant PULI_FACTORY_CLASS

  .

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
`

    $ composer update

And the package I needed is installed

**Comment by webmozart** [comment] 2016-02-19 19:42
Thank you for reporting this @devigner! This is really strange. Could you push some simple repository that reproduces the problem for you, together with some steps that let me reproduce it as well?

**Comment by devigner** [comment] 2016-02-19 21:52
My testing environment https://github.com/devigner/devigner.io

I've done some hacking and currently I'm looking at https://github.com/puli/composer-plugin/blob/master/src/PuliPlugin.php . My guess is that "composer require" isn't firing an event that is registered inside the plugin.

Some deeper hacking is needed.

**Comment by devigner** [comment] 2016-02-19 21:55
Summary to replicate (the package I'm installing is only as example):

`$ composer require predis/predis`

Will throw the exception

`$ composer update`

Fixes it. Because PuliPlugin is triggered

**Comment by pkruithof** [comment] 2016-02-26 13:22
@webmozart I think I know how this is happening:

Symfony3 requires [ocramius/ProxyManager](https://github.com/ocramius/ProxyManager), which in turn depends on [ocramius/PackageVersions](https://github.com/ocramius/PackageVersions), which also has a composer plugin. That plugin [overwrites the autoload file](https://github.com/Ocramius/PackageVersions/blob/master/src/PackageVersions/Installer.php#L165-L175), and with it the constant.

A workaround is to run `composer dump` to recreate the autoload file without triggering the other plugin. Both `install` and `update` trigger both, which causes the problem:

**Works**
```
%> composer dump
Generating autoload files
Generating the "PULI_FACTORY_CLASS" constant
Registering "Puli\GeneratedPuliFactory" with the class-map autoloader
```

**Breaks**
```
%> composer run-script post-install-cmd
Synchronizing Puli with Composer
Deleting the ".puli" directory
Running "puli build"
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

                                                                  
  [Symfony\Component\Debug\Exception\ContextErrorException]       
  Warning: constant(): Couldn't find constant PULI_FACTORY_CLASS  
                                                                  

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

                                                                             
  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:  
                                                                             
    [Symfony\Component\Debug\Exception\ContextErrorException]                
    Warning: constant(): Couldn't find constant PULI_FACTORY_CLASS           
                                                                             
  .                                                                          
                                                                             

run-script [--timeout TIMEOUT] [--dev] [--no-dev] [-l|--list] [--] [<script>] [<args>]...
```

/cc @ocramius

**Comment by devigner** [comment] 2016-02-26 13:33
Strange, I haven't got that package installed. I've tested the following commands:

**Do not break:**
`composer run-script post-install-cmd`
`composer run-script post-update-cmd`
`composer install`
`composer update`

Is there a command to dispatch the same events as `composer require` does?

**Comment by pkruithof** [comment] 2016-02-26 13:35
It comes with Symfony3 via the following route:

```
symfony/symfony
  -> symfony/proxy-manager-bridge
    -> ocramius/proxy-manager
      -> ocramius/package-versions
```

**Comment by Ocramius** [comment] 2016-02-26 13:39
> That plugin overwrites the autoload file, and with it the constant.

I suppose the problem is (specifically) with https://github.com/Ocramius/PackageVersions/blob/25f302d5c9a83bb9f62108d9183fc293c0ffe2ca/src/PackageVersions/Installer.php#L173 ?

I can avoid re-dumping the autoloader, but that causes additional I/O at runtime for me.

The problem may indeed be that I'm calling the autoload dumper manually there. If there was a more "plugin-friendly" way of doing it, I'd do so.

**Comment by pkruithof** [comment] 2016-02-26 13:44
I'm not familiar with what the re-dump does exactly, but looking at Composer's dump process I don't see a way to inject the constant without editing the file in code (as it is done right now).

By the way, if the order of the plugins was the other way around this wouldn't be an issue right now.

**Comment by Ocramius** [comment] 2016-02-26 13:45
Order of execution is the worst coupling though. I'm fine with removing the autoload dumping for now, until we find a different solution.

**Comment by Ocramius** [comment] 2016-02-26 13:54
Please see if https://github.com/Ocramius/PackageVersions/pull/15 fixes this issue

**Comment by pkruithof** [comment] 2016-02-26 13:58
> Order of execution is the worst coupling though.

I agree.

Ocramius/PackageVersions#15 indeed fixes it, thanks for the quick response!

**Comment by Ocramius** [comment] 2016-02-26 14:05
Fixed via https://github.com/Ocramius/PackageVersions/releases/tag/1.0.3

While this may mitigate the symptom, the issue is still there and quite valid, I'd say.

**Comment by webmozart** [comment] 2016-03-04 08:36
@Ocramius Thanks a lot for the fast response :) What do you recommend?

**Closed** 2016-03-04 08:36 UTC
Labels: Bug, Composer Plugin

**Comment by Ocramius** [comment] 2016-03-04 16:36
@webmozart I recommend:

 * that this issue should be re-opened (symptom fixed, but initial cause wasn't fixed)
 * that puli triggers autoload dumping and also fires the dump-autoload related events when doing so
 * that this is brought up to the composer development issue tracker, since this may happen again (many times) in future.
